---
wp_version: 6.0.2
wp_install_dir: '/var/www/html'
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: wordpress
wp_db_charset: 'utf8'
wp_db_collate: ''
wp_table_prefix: 'wp_'
wp_debug: false
wp_admin_email: "addzt@yandex.ru"
wp_webserver: nginx
site_name: "addzt.ru"

