---
- name: Figure out PHP FPM socket location
  shell: dpkg -l | grep php-fpm  | awk '{print $3}' | grep -o '[0-9]\.[0-9]' | head -n 1
  register: 'php_ver'

- name: Start service php{{ php_ver.stdout }}
  service:
    name: "php{{ php_ver.stdout }}-fpm"
    state: started

- name: Start service nginx
  service:
    name: "nginx"
    state: started

- name: Copy virtual host configuration file
  template:
    src: "nginx-vhost.j2"
    dest: "/etc/nginx/sites-available/{{ site_name }}"
    owner: root
    group: root
    mode: 0644

- name: Symlink virtual host configuration file from sites-available to sites-enabled
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ site_name }}"
    dest: "/etc/nginx/sites-enabled/{{ site_name }}"
    owner: root
    group: root
    mode: 0644

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
  - restart nginx
