---
 - name: Install Gitlab
   hosts: gitlab
   gather_facts: true
   become: true
   become_method: sudo
   become_user: root
   remote_user: ubuntu
   roles:
   - gitlab
   environment:
     GITLAB_ROOT_PASSWORD: "SecretP@ssw0rd"
     GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: "LnAsx-pSbHqxkQxzwoTT"